#!/bin/bash

if [ $1 == "configure" ]; then

	if [ -f "/boot/bootcode.bin.xbian" ]; then
		rm /boot/bootcode.bin.xbian
	fi

	if [ -f "/boot/fixup.dat.xbian" ]; then
		rm /boot/fixup.dat.xbian
	fi

	if [ -f "/boot/start.elf.xbian" ]; then
		rm /boot/start.elf.xbian
	fi

	[ -e /usr/lib/vfp ] && rm -f /usr/lib/vfp

	ldconfig &>/dev/null

fi

grep -q ^emmc_pll_core /boot/config.txt || echo "emmc_pll_core=0" >> /boot/config.txt

echo "xbian-package-firmware" >>  /var/run/reboot-required || :
