#!/bin/bash

if [ $1 == "configure" ]; then

	if [ -f "/boot/bootcode.bin.xbian" ]; then
		rm /boot/bootcode.bin.xbian
	fi

	if [ -f "/boot/fixup.dat.xbian" ]; then
		rm /boot/fixup.dat.xbian
	fi

	if [ -f "/boot/start.elf.xbian" ]; then
		rm /boot/start.elf.xbian
	fi

	[ -e /usr/lib/vfp ] && rm -f /usr/lib/vfp

	ldconfig &>/dev/null

fi

touch /var/run/reboot-required || :
